name: Build and deploy Portfolio Website

on:
  push:
    branches:
      - main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH connection
        run: ssh -T git@github.com

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Create known_hosts file
        run: touch ~/.ssh/known_hosts

      - name: Set up Git
        run: |
          git config --global user.email "npozdeyev@gmail.com"
          git config --global user.name "PNik1ta"
          ssh-keyscan github.com >> ~/.ssh/known_hosts


      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install angular-cli-ghpages
        run: npm install -g angular-cli-ghpages

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: ng build --base-href "https://pnik1ta.github.io/Portfolio-Website/" --deploy-url="https://pnik1ta.github.io/Portfolio-Website/"

      - name: Deploy the application
        run: ngh --dir dist/portfolio-site --no-silent